services:

  next:
    build:
      context: ./next.js
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "3000:3000"
    volumes:
      - ./next.js:/app
      - /app/node_modules
    networks:
      - blog-network

  react:
    build:
      context: ./react.js
      dockerfile: Dockerfile
    container_name: blog_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react.js:/app
      - /app/node_modules
    networks:
      - blog-network

  nginx:
    build:
      context: ./nginx
    container_name: blog_nginx
    depends_on:
      - react
      - next
    ports:
      - "8081:80"
    networks:
      - nginx-proxy-manager-stack_default
      - blog-network

networks:
  blog-network:
    driver: bridge
  nginx-proxy-manager-stack_default:
    external: true