events {}

http {
    server {
        listen 80;
        server_name blog-app.yohannimation.fr;

        # Proxy vers le frontend React
        location / {
            proxy_pass http://react:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Proxy vers le backend Next.js
        location /api/ {
            proxy_pass http://next:3000/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
